apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: git-push-pingcap-tiproxy
  labels:
    type: github-branch-push
    github-owner: pingcap
    github-repo: tiproxy
spec:
  interceptors:
    - name: filter on repo owner and name and branches
      ref: { name: cel }
      params:
        - name: filter
          value: >-
            body.repository.full_name == 'pingcap/tiproxy'
            &&
            body.ref.matches('^refs/heads/(main|master|release-[0-9]+[.][0-9]+)$')
  bindings:
    - ref: github-branch-push
    - { name: component, value: $(body.repository.name) }
    - { name: profile, value: release }
    - { name: timeout, value: 30m }
    - { name: source-ws-size, value: 10Gi }
    - { name: builder-resources-memory, value: 16Gi }
    - { name: builder-resources-cpu, value: "4" }
  template:
    ref: build-component-all-platforms
