apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: tag-create-pingcap-tiproxy
  labels:
    type: github-tag-create
    github-owner: pingcap
    github-repo: tiproxy
spec:
  interceptors:
    - name: filter on repo owner and name and tags
      ref: { name: cel }
      params:
        - name: filter
          value: >-
            body.repository.full_name == 'pingcap/tiproxy'
            &&
            body.ref.matches('^v[0-9]+[.][0-9]+[.][0-9]+(-(alpha|beta|nextgen)([.][0-9]+.*)?)?$')
  bindings:
    - ref: github-tag-create
    - { name: component, value: $(body.repository.name) }
    - { name: profile, value: release }
    - { name: timeout, value: 30m }
    - { name: source-ws-size, value: 10Gi }
    - { name: builder-resources-memory, value: 32Gi }
    - { name: builder-resources-cpu, value: "8" }
  template:
    ref: build-component-all-platforms
