## You should run it firstly:
## kubectl port-forward -n ee-cd svc/el-public 8080

### pingcap/tiproxy push on main branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/main",
    "before": "00000000000000000000000000000000000000000",
    "after": "5273b42a131f4fb9dac95606b89b15f20fc85fe4",
    "ref_type": "branch",
    "repository": {
        "name": "tiproxy",
        "clone_url": "https://github.com/pingcap/tiproxy",
        "owner": {
            "login": "pingcap"
        }
    }
}
