## You should run it firstly:
## kubectl port-forward -n ee-cd svc/el-public 8080

### pingcap/advanced-statefulset: push on master branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/master",
    "before": "00000000000000000000000000000000000000000",
    "after": "00595b4ef4ac4f08e16c930994ccc611c7ee6c64",
    "ref_type": "branch",
    "repository": {
        "name": "advanced-statefulset",
        "clone_url": "https://github.com/pingcap/advanced-statefulset.git",
        "owner": {
            "login": "pingcap"
        }
    }
}

########################
### pingcap/advanced-statefulset: create a new version tag
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: create

{
  "ref": "v0.5.1-alpha.1",
  "ref_type": "tag",
  "repository": {
    "name": "advanced-statefulset",
    "clone_url": "https://github.com/pingcap/advanced-statefulset.git",
    "owner": {
      "login": "pingcap"
    }
  }
}
