apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: rust
      image: "hub.pingcap.net/jenkins/centos7_golang-1.13_rust"
      tty: true
      resources:
        requests:
          memory: 8Gi
          cpu: "2"
        limits:
          memory: 16Gi
          cpu: "6"
      command: [/bin/sh, -c]
      args: [cat]
      env:
        - name: GOPATH
          value: /share/.go
        - name: GOCACHE
          value: /share/.cache/go-build
      volumeMounts:
        - name: gocache
          mountPath: /share/.cache/go-build
        - name: gopathcache
          mountPath: /share/.go
    - name: net-tool
      image: wbitt/network-multitool
      tty: true
      resources:
        limits:
          memory: 128Mi
          cpu: 200m
  volumes:
    - name: gopathcache
      persistentVolumeClaim:
        claimName: gopathcache
    - name: gocache
      persistentVolumeClaim:
        claimName: gocache
