## You should run it firstly:
## kubectl port-forward -n ee-cd svc/el-public 8080

### pingcap/tidb-tools push on master branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/master",
    "before": "00000000000000000000000000000000000000000",
    "after": "c4bdf178b3d6ae0242332aa7ef8448b74eb5b45c",
    "ref_type": "branch",
    "repository": {
        "name": "tidb-tools",
        "clone_url": "https://github.com/pingcap/tidb-tools",
        "owner": {
            "login": "pingcap"
        }
    }
}

### pingcap/tidb-tools version tag created
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: create

{
  "ref": "v7.5.0",
  "ref_type": "tag",
  "repository": {
    "name": "tidb-tools",
    "clone_url": "https://github.com/pingcap/tidb-tools.git",
    "owner": {
      "login": "pingcap"
    }
  }
}
