apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pingcap-create-github-releases
spec:
  description: create github releases on product GitHub repositories.
  params:
    - name: version
      description: the release semver tag name, e.g. v5.0.0
  workspaces:
    - name: github
      description: Must includes a key `token`
  steps:
    - name: create-releases
      image: docker.io/denoland/deno:alpine-2.2.5
      script: |
        deno run --allow-all https://github.com/PingCAP-QE/ci/raw/main/scripts/flow/ga/create_github_release.ts \
          --version="$(params.version)" \
          --token="$(cat $(workspaces.github.path)/token)"
    - name: create-branches
      image: docker.io/denoland/deno:alpine-2.2.5
      onError: continue # it's not so important.
      script: |
        deno run --allow-net https://github.com/PingCAP-QE/ci/raw/main/scripts/flow/ga/create-patch-release-branches.ts \
          --version="$(params.version)" \
          --token="$(cat $(workspaces.github.path)/token)"
