apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tag-rc2ga-on-oci-artifacts
spec:
  description: include images and non-image artifacts.
  params:
    - name: rc-version
      description: >
        the rc tag of artifacts repos, example: v1.1.1-pre
    - name: ga-version
      description: >
        the GA publish tag of artifacts repos, example: v1.1.1
    - name: force
      default: "false"
      description: force to create tag whether it existed or not.
  steps:
    - name: run
      image: ghcr.io/pingcap-qe/cd/utils/release:v2025.8.17-13-ga5750d9
      script: |
        #! /usr/bin/env bash
        set -ex

        rc_ver="$(params.rc-version)"
        ga_ver="$(params.ga-version)"
        registry="hub.pingcap.net"

        wget -c --tries=3 https://github.com/PingCAP-QE/ci/raw/main/scripts/artifacts/tag-rc2ga-on-repos.sh
        chmod +x tag-rc2ga-on-repos.sh

        ./tag-rc2ga-on-repos.sh "$rc_ver" "$ga_ver" "$registry" $(params.force) results.yaml
        cat results.yaml
