apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: nodejs
      image: node:14.21-alpine
      securityContext:
        privileged: true
      tty: true
      resources:
        requests:
            memory: "2Gi"
            cpu: "1"
        limits:
            memory: "8Gi"
            cpu: "4"
