apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: git-push-pingcap-tidb-build-enterprise-without-plugins
  labels:
    type: github-branch-push
    github-owner: pingcap
    github-repo: tidb
    profile: enterprise-without-plugins
spec:
  interceptors:
    - name: filter on repo owner and name and branches
      ref: { name: cel }
      params:
        - name: filter
          # support branches:
          # - feature/release-X.Y-*
          value: >-
            body.repository.full_name == 'pingcap/tidb'
            &&
            body.ref.matches('^refs/heads/(feature/release-[7-9]+[.][0-9]+-.*)$')

  bindings:
    - ref: github-branch-push
    - ref: gcp-classic-build-params
    - { name: component, value: $(body.repository.name) }
    - { name: os, value: linux }
    - { name: profile, value: enterprise-without-plugins }
    - { name: timeout, value: 45m }
    - { name: source-ws-size, value: 50Gi }
    - { name: builder-resources-memory, value: 24Gi }
    - { name: builder-resources-cpu, value: "6" }
  template:
    ref: build-component-linux
