apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: runner
      image: ghcr.io/pingcap-qe/cd/builders/tiflash:v2025.4.15-rocky8-llvm-17.0.6-v2
      imagePullPolicy: Always
      command:
        - "cat"
      tty: true
      # Notice: not set the resources limit, because limit will make unit test failed
      resources:
        requests:
          memory: "32Gi"
          cpu: "12"
          ephemeral-storage: 20Gi
      volumeMounts:
        - mountPath: "/tmp"
          name: "tmp"
          readOnly: false
        - mountPath: "/tmp-memfs"
          name: "tmp-memfs"
          readOnly: false
        - mountPath: "/home/jenkins"
          name: "jenkins-home"
          readOnly: false
  volumes:
    - name: "tmp"
      emptyDir: {}
    - name: "tmp-memfs"
      emptyDir:
        medium: Memory
    - name: "jenkins-home"
      emptyDir: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
