apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  initContainers:
    - name: init-mysql-config
      image: "ghcr.io/pingcap-qe/ci/jenkins:v2026.4.12-10-gc29110c-go1.25"
      command:
        - sh
        - -c
        - |
          echo "[client]" > /mysql-config/.my.cnf
          echo "ssl-mode=DISABLED" >> /mysql-config/.my.cnf
      volumeMounts:
        - mountPath: "/mysql-config"
          name: "mysql-config-volume"
  containers:
    - name: golang
      image: "ghcr.io/pingcap-qe/ci/jenkins:v2026.4.12-10-gc29110c-go1.25"
      command: [tini, --, bash]
      tty: true
      resources:
        requests:
          memory: 12Gi
          cpu: "4"
        limits:
          memory: 16Gi
          cpu: "6"
      volumeMounts:
        - mountPath: "/home/jenkins/.my.cnf"
          name: "mysql-config-volume"
          subPath: ".my.cnf"
    - name: utils
      image: ghcr.io/pingcap-qe/cd/utils/release:v2025.10.12-7-gfdd779c
      tty: true
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          cpu: "1"
          memory: 4Gi
    - name: mysql1
      image: "docker.io/library/mysql:5.7"
      tty: true
      resources:
        limits:
          memory: 4Gi
          cpu: "2"
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: '123456'
      args:
        - "--ssl=ON"
        - "--log-bin"
        - "--binlog-format=ROW"
        - "--enforce-gtid-consistency=ON"
        - "--gtid-mode=ON"
        - "--server-id=1"
        - "--default-authentication-plugin=mysql_native_password"
    - name: mysql2
      image: "docker.io/library/mysql:5.7"
      tty: true
      resources:
        limits:
          memory: 4Gi
          cpu: "2"
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: '123456'
        - name: MYSQL_TCP_PORT
          value: '3307'
      args:
        - "--ssl=ON"
        - "--log-bin"
        - "--binlog-format=ROW"
        - "--enforce-gtid-consistency=ON"
        - "--gtid-mode=ON"
        - "--server-id=1"
        - "--default-authentication-plugin=mysql_native_password"
  volumes:
    - name: mysql-config-volume
      emptyDir: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
