apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: golang
      image: "hub.pingcap.net/jenkins/centos7_golang-1.20:latest"
      tty: true
      resources:
        requests:
          memory: 12Gi
          cpu: "4"
        limits:
          memory: 16Gi
          cpu: "6"
      volumeMounts:
        - mountPath: /tmp
          name: volume-0
    - name: golang121
      image: "hub.pingcap.net/jenkins/centos7_golang-1.21:latest"
      tty: true
      resources:
        requests:
          memory: 12Gi
          cpu: "4"
        limits:
          memory: 16Gi
          cpu: "6"
      volumeMounts:
        - mountPath: /tmp
          name: volume-0
    - image: hub.pingcap.net/jenkins/zookeeper
      imagePullPolicy: IfNotPresent
      name: zookeeper
      resources:
          requests:
            cpu: 2000m
            memory: 4Gi
          limits:
            cpu: 4000m
            memory: 8Gi
      tty: true
      volumeMounts:
        - mountPath: /tmp
          name: volume-0
    - env:
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "1073741824"
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "1073741824"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "127.0.0.1"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: ZK
          value: "zk"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "127.0.0.1:2181"
      image: hub.pingcap.net/jenkins/kafka
      imagePullPolicy: IfNotPresent
      name: kafka
      resources:
        requests:
          cpu: 4000m
          memory: 6Gi
        limits:
          cpu: 4000m
          memory: 6Gi
      tty: true
      volumeMounts:
        - mountPath: /tmp
          name: volume-0
    - name: net-tool
      image: hub.pingcap.net/jenkins/network-multitool
      tty: true
      resources:
        limits:
          memory: 128Mi
          cpu: 100m
  volumes:
    - emptyDir:
        medium: Memory
      name: volume-0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
