apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: sync-owners-for-hotfix-branch
spec:
  params:
    - name: git-url
      description: The git repository full url
    - name: git-ref
      description: The git ref
      default: main
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: TaskRun
      metadata:
        generateName: create-pr-to-sync-owners-for-hotfix-
        annotations:
          "tekton.dev/git-status": "true"
          "tekton.dev/git-repo": $(tt.params.git-url)
          "tekton.dev/git-revision": $(tt.params.git-ref)
      spec:
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: branch
            value: $(tt.params.git-ref)
        taskRef:
          kind: Task
          name: create-pr-to-sync-owners
        workspaces:
          - name: github
            secret:
              secretName: github
