apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: build-component-darwin
spec:
  params:
    - name: git-url
      description: The git repository full url
    - name: git-refspec
      default: +refs/heads/*:refs/heads/*
    - name: git-revision
      description: The git revision
    - name: git-ref
      description: The git branch
    - name: component
      description: component name, tidb|tikv|pd|tiflow|tiflash, etc...
    - name: os
      default: darwin
    - name: profile
      description: build target profile
      default: release
    - name: registry
      default: hub.pingcap.net
    - name: timeout
      description: pipeline run timeout
      default: 2h
    - name: source-ws-size
      description: workspace size for source.
      default: 20Gi
    - name: ce-context
      description: cloud event context.
      default: "{}"
    - name: force-builder-image
      description: force use the builder image to prepare container to build binaries.
      default: ""
    - name: boskos-server-url
      default: "http://boskos"
    - name: publisher-url
      default: "https://publisher.pingcap.net"
    - name: git-instead-of
      description: |
        Configure Git to use the `insteadOf` feature to speed up cloning.
        You can specify multiple `insteadOf` configurations separated by commas.
        For example: insteadof1 => new1, insteadof2 => new2
      default: ""
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: bp-$(tt.params.component)-$(tt.params.profile)-$(tt.params.os)-amd64-
        annotations:
          "tekton.dev/ce-context": $(tt.params.ce-context)
          "tibuild.pingcap.net/git-repo": $(tt.params.git-url)
          "tibuild.pingcap.net/git-ref": $(tt.params.git-ref)
          "tibuild.pingcap.net/git-revision": $(tt.params.git-revision)
          "tibuild.pingcap.net/component": $(tt.params.component)
          "tibuild.pingcap.net/profile": $(tt.params.profile)
          "tibuild.pingcap.net/platform": $(tt.params.os)/amd64
      spec:
        pipelineRef:
          name: pingcap-build-package-$(tt.params.os)
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-refspec
            value: $(tt.params.git-refspec)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: git-ref
            value: $(tt.params.git-ref)
          - name: component
            value: $(tt.params.component)
          - name: profile
            value: $(tt.params.profile)
          - name: os
            value: $(tt.params.os)
          - name: arch
            value: amd64
          - name: registry
            value: $(tt.params.registry)
          - name: force-builder-image
            value: $(tt.params.force-builder-image)
          - name: boskos-server-url
            value: $(tt.params.boskos-server-url)
          - name: publisher-url
            value: $(tt.params.publisher-url)
          - name: git-instead-of
            value: $(tt.params.git-instead-of)
        taskRunTemplate:
          podTemplate:
            nodeSelector:
              kubernetes.io/arch: amd64
        taskRunSpecs:
          - pipelineTaskName: checkout
            serviceAccountName: github-bot
          - pipelineTaskName: checkout-ext
            serviceAccountName: github-bot
          - pipelineTaskName: build-binaries
            serviceAccountName: image-releaser
        timeouts:
          pipeline: $(tt.params.timeout)
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                storageClassName: ${STORAGE_CLASSNAME_RWO_AMD64}
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: $(tt.params.source-ws-size)
          - name: mac-ssh-credentials
            secret:
              secretName: mac-ssh-credentials
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: bp-$(tt.params.component)-$(tt.params.profile)-$(tt.params.os)-arm64-
        annotations:
          "tekton.dev/ce-context": $(tt.params.ce-context)
          "tibuild.pingcap.net/git-repo": $(tt.params.git-url)
          "tibuild.pingcap.net/git-ref": $(tt.params.git-ref)
          "tibuild.pingcap.net/git-revision": $(tt.params.git-revision)
          "tibuild.pingcap.net/component": $(tt.params.component)
          "tibuild.pingcap.net/profile": $(tt.params.profile)
          "tibuild.pingcap.net/platform": $(tt.params.os)/arm64
      spec:
        pipelineRef:
          name: pingcap-build-package-$(tt.params.os)
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-refspec
            value: $(tt.params.git-refspec)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: git-ref
            value: $(tt.params.git-ref)
          - name: component
            value: $(tt.params.component)
          - name: profile
            value: $(tt.params.profile)
          - name: os
            value: $(tt.params.os)
          - name: arch
            value: arm64
          - name: registry
            value: $(tt.params.registry)
          - name: force-builder-image
            value: $(tt.params.force-builder-image)
          - name: boskos-server-url
            value: $(tt.params.boskos-server-url)
          - name: publisher-url
            value: $(tt.params.publisher-url)
          - name: git-instead-of
            value: $(tt.params.git-instead-of)
        taskRunTemplate:
          podTemplate:
            nodeSelector:
              kubernetes.io/arch: amd64 # just as a remtoe execute client.
        taskRunSpecs:
          - pipelineTaskName: checkout
            serviceAccountName: github-bot
          - pipelineTaskName: checkout-ext
            serviceAccountName: github-bot
          - pipelineTaskName: build-binaries
            serviceAccountName: image-releaser
        timeouts:
          pipeline: $(tt.params.timeout)
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                storageClassName: ${STORAGE_CLASSNAME_RWO_AMD64}
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: $(tt.params.source-ws-size)
          - name: mac-ssh-credentials
            secret:
              secretName: mac-ssh-credentials
