apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: collect-multi-arch-image
spec:
  params:
    - name: image_url
      description: The image full url for pull
    - name: tag
      description: The image tag
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: TaskRun
      metadata:
        generateName: auto-compose-multi-arch-image-run-
      spec:
        serviceAccountName: image-releaser
        taskRef:
          name: multi-arch-image-collect
        params:
          - name: image_url
            value: "$(tt.params.image_url)"
          - name: release_tag_suffix
            value: release
