# yaml-language-server: $schema=https://github.com/redhat-developer/vscode-tekton/raw/refs/heads/main/scheme/triggers.tekton.dev/v1beta1_TriggerTemplate.json
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: notify-successful-image-delivery-tidbx
spec:
  params:
    - name: data
  resourceTemplates:
    - apiVersion: tekton.dev/v1
      kind: TaskRun
      metadata:
        generateName: pingcap-notify-for-tidbx-images-
      spec:
        params:
          - name: src
            value: $(tt.params.data)
        taskRef:
          name: pingcap-notify-for-tidbx-images
        workspaces:
          - name: notify-config
            secret:
              secretName: image-delivery-notify-config-tidbx
