apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: github-push-build-community-fts-linux # Darwin builds are still on inner KSYun cluster
  labels:
    type: github-branch-push
    profile: community
spec:
  interceptors:
    - name: filter on repo and branch
      ref: { name: cel }
      params:
        - name: filter
          value: >-
            body.repository.full_name in ['pingcap/tidb', 'pingcap/tiflash']
            &&
            body.ref.matches('^refs/heads/feature/fts$')
        - name: overlays
          value:
            - key: timeout
              expression: >-
                {
                'pingcap/tidb': '1h',
                'pingcap/tiflash': '3h',
                }[body.repository.full_name]
            - key: source-ws-size
              expression: >-
                {
                'pingcap/tidb': '50Gi',
                'pingcap/tiflash': '100Gi',
                }[body.repository.full_name]
            - key: builder-resources-cpu
              expression: >-
                {
                'pingcap/tidb': '8',
                'pingcap/tiflash': '16',
                }[body.repository.full_name]
            - key: builder-resources-memory
              expression: >-
                {
                'pingcap/tidb': '32Gi',
                'pingcap/tiflash': '64Gi',
                }[body.repository.full_name]
  bindings:
    - ref: github-branch-push
    - ref: gcp-classic-build-params
    - name: builder-resources-cpu
      value: $(extensions.builder-resources-cpu)
    - name: builder-resources-memory
      value: $(extensions.builder-resources-memory)
    - { name: component, value: $(body.repository.name) }
    - { name: profile, value: release }
    - { name: source-ws-size, value: $(extensions.source-ws-size) }
    - { name: timeout, value: $(extensions.timeout) }

  template:
    ref: build-component-linux
