apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: github-push-build-ng
  labels:
    type: github-branch-push
    profile: next-gen
spec:
  interceptors:
    - name: filter on repo and branches
      ref: { name: cel }
      params:
        - name: filter
          value: >-
            (
              body.repository.full_name in [
                'pingcap/ticdc',
                'pingcap/tidb',
                'pingcap/tiflash',
                'pingcap/tiproxy',
                'tidbcloud/cloud-storage-engine',
                'tikv/pd',
              ] && body.ref.matches('^refs/heads/(release-nextgen-[0-9]+)$')
            ) || (
              body.repository.full_name in [
                'pingcap/ticdc',
                'pingcap/tidb',
                'pingcap/tiflash',
                'tikv/pd',
              ] && && body.ref == 'refs/heads/master'
            ) || (
              body.repository.full_name in [
                'tidbcloud/cloud-storage-engine',
              ] && && body.ref == 'dedicated'
            ) || (
              body.repository.full_name in [
                'pingcap/tidb',
                'pingcap/tiflash',
              ] && && body.ref == 'refs/heads/feature/fts'
            )
        - name: overlays
          value:
            - key: resource-config
              expression: >-
                {
                  'pingcap/tiproxy': {
                    'timeout': '30m',
                    'sourceWsSize': '20Gi',
                    'builderResourcesCpu': '3',
                    'builderResourcesMemory': '12Gi',
                  },
                  'pingcap/ticdc': {
                    'timeout': '20m',
                    'sourceWsSize': '50Gi',
                    'builderResourcesCpu': '3',
                    'builderResourcesMemory': '12Gi',
                  },
                  'pingcap/tidb': {
                    'timeout': '45m',
                    'sourceWsSize': '50Gi',
                    'builderResourcesCpu': '6',
                    'builderResourcesMemory': '24Gi',
                  },
                  'pingcap/tiflash': {
                    'timeout': '2h',
                    'sourceWsSize': '100Gi',
                    'builderResourcesCpu': '12',
                    'builderResourcesMemory': '48Gi',
                  },
                  'tikv/pd': {
                    'timeout': '20m',
                    'sourceWsSize': '50Gi',
                    'builderResourcesCpu': '6',
                    'builderResourcesMemory': '24Gi',
                  },
                  'tidbcloud/cloud-storage-engine': {
                    'timeout': '30m',
                    'sourceWsSize': '100Gi',
                    'builderResourcesCpu': '12',
                    'builderResourcesMemory': '48Gi',
                  },
                }[body.repository.full_name]
            - key: component
              expression: >-
                body.repository.full_name == 'tidbcloud/cloud-storage-engine'
                ?
                'tikv'
                :
                body.repository.name
            - key: profile
              expression: >-
                body.repository.full_name == 'pingcap/tiproxy' ? 'release' : 'next-gen'

  bindings:
    - ref: github-branch-push
    - ref: gcp-ng-build-params
    - { name: component, value: $(extensions.component) }
    - { name: profile, value: $(extensions.profile) }
    - { name: os, value: linux }

  template:
    ref: build-component-linux
