apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: jenkins-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomize-config.yaml