apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: jenkins-values
    files:
      - values1.yaml=values-controller.yaml
      - values2.yaml=values-persistence.yaml
      - values3.yaml=values-JCasC.yaml
      - values4.yaml=values-JCasC-jobs.yaml
      - values5.yaml=values-agent.yaml
configurations:
  - kustomize-config.yaml
