apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
spec:
  releaseName: jenkins
  chart:
    spec:
      chart: jenkins
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
      version: "4.1.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  test:
    enable: true
    ignoreFailures: false
  valuesFrom:
    - { kind: ConfigMap, name: jenkins-values, valuesKey: values1.yaml }
    - { kind: ConfigMap, name: jenkins-values, valuesKey: values2.yaml }
    - { kind: ConfigMap, name: jenkins-values, valuesKey: values3.yaml }
    - { kind: ConfigMap, name: jenkins-values, valuesKey: values4.yaml }
    - { kind: ConfigMap, name: jenkins-values, valuesKey: values5.yaml }
