apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: gcp-dev-build-params # only use in GCP clusters for dev-builds
spec:
  params:
    # Reserved for future mac/darwin builds. GCP fake-github triggers currently only support linux builds.
    - { name: boskos-server-url, value: http://boskos.test-pods.svc.cluster.local }
    - { name: builder-resources-cpu, value: $(extensions.resource-config.cpu) }
    - { name: builder-resources-memory, value: $(extensions.resource-config.memory) }
    - { name: component, value: $(extensions.component) }
    - { name: force-builder-image, value: $(extensions.custom-params.builder-image) }
    - { name: profile, value: $(extensions.custom-params.profile) }
    - { name: publisher-url, value: "" } # no need publish in dev-builds
    - { name: registry, value: $(extensions.registry) }
    - { name: source-ws-size, value: $(extensions.resource-config.sourceWsSize) }
    - { name: timeout, value: $(extensions.resource-config.timeout) }
    - { name: external-git-ref, value: $(extensions.custom-params.external-git-ref) }
