apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: tag-create-pingcap-operator
  labels:
    type: github-tag-create
    github-owner: pingcap
    github-repo: operator
spec:
  interceptors:
    - name: filter on repo owner and name and tags
      ref:
        name: cel
      params:
        - name: filter
          value: >-
            body.repository.full_name == 'pingcap/tidb-operator'
            &&
            body.ref.matches('^v[0-9]+[.][0-9]+[.][0-9]+(-.+)?$')
  bindings:
    - ref: github-tag-create
    - { name: component, value: $(body.repository.name) }
    - { name: os, value: linux }
    - { name: profile, value: release }
    - { name: timeout, value: 30m }
    - { name: source-ws-size, value: 10Gi }
    - { name: builder-resources-memory, value: 8Gi }
    - { name: builder-resources-cpu, value: "2" }
  template:
    ref: build-component
