apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: golang
      image: "ghcr.io/pingcap-qe/ci/jenkins:v2025.12.28-2-g97bb688-go1.25"
      tty: true
      resources:
        limits:
          memory: 24Gi
          cpu: "6"
  volumes:
    - name: workspace-volume
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 150Gi
            storageClassName: hyperdisk-rwo
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
