apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: golang
      image: hub.pingcap.net/jenkins/golang-tini:1.23
      tty: true
      args:
        - cat
      resources:
        requests:
          memory: 12Gi
          cpu: "4"
        limits:
          memory: 16Gi
          cpu: "6"
    - name: mysql1
      image: "hub.pingcap.net/jenkins/mysql:5.7"
      tty: true
      resources:
        limits:
          memory: 4Gi
          cpu: 2
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
      args:
        - "--ssl=ON"
        - "--log-bin"
        - "--binlog-format=ROW"
        - "--enforce-gtid-consistency=ON"
        - "--gtid-mode=ON"
        - "--server-id=1"
        - "--default-authentication-plugin=mysql_native_password"
    - name: mysql2
      image: "registry-mirror.pingcap.net/library/mysql:8.0.21"
      tty: true
      resources:
        limits:
          memory: 4Gi
          cpu: 2
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_TCP_PORT
          value: "3307"
      args:
        - "--ssl=ON"
        - "--log-bin"
        - "--binlog-format=ROW"
        - "--enforce-gtid-consistency=ON"
        - "--gtid-mode=ON"
        - "--server-id=1"
        - "--default-authentication-plugin=mysql_native_password"
    - name: net-tool
      image: hub.pingcap.net/jenkins/network-multitool
      tty: true
      resources:
        limits:
          memory: 128Mi
          cpu: 100m
    - name: report
      image: hub.pingcap.net/jenkins/python3-requests:latest
      tty: true
      resources:
        limits:
          memory: 256Mi
          cpu: 100m
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
