apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: tag-create-pingcap-tidb-ctl
  labels:
    type: github-tag-create
    github-owner: pingcap
    github-repo: tidb-ctl
spec:
  interceptors:
    - name: filter on repo owner and name
      ref:
        name: cel
      params:
        - name: filter
          value: >-
            body.repository.full_name == 'pingcap/tidb-ctl'
            &&
            body.ref.matches('^v[0-9]+[.][0-9]+[.][0-9]+$')
  bindings:
    - ref: github-tag-create
    - { name: component, value: $(body.repository.name) }
    - { name: profile, value: release }
    - { name: timeout, value: 1h }
    - { name: source-ws-size, value: 10Gi }
    - { name: builder-resources-memory, value: 4Gi }
    - { name: builder-resources-cpu, value: "2" }
  template:
    ref: build-component-all-platforms
