## You should run it firstly:
## kubectl port-forward -n ee-cd svc/el-public 8080

### pingcap/tidb-ctl push on master branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/master",
    "before": "00000000000000000000000000000000000000000",
    "after": "9c165585d38e16591d459f21c0c82b9518747aba",
    "ref_type": "branch",
    "repository": {
        "name": "tidb-ctl",
        "clone_url": "https://github.com/pingcap/tidb-ctl",
        "owner": {
            "login": "pingcap"
        }
    }
}

### pingcap/tidb-ctl version tag created
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: create

{
  "ref": "v7.5.0",
  "ref_type": "tag",
  "repository": {
    "name": "tidb-ctl",
    "clone_url": "https://github.com/pingcap/tidb-ctl.git",
    "owner": {
      "login": "pingcap"
    }
  }
}
