apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: pr-labeled-with-needs-ok-to-test
  labels:
    type: github-pr
spec:
  interceptors:
    - name: filter on repo owner and name and tags
      ref: { name: cel }
      params:
        - name: filter
          value: >-
            body.action == 'labeled'
            &&
            body.label.name in ['needs-ok-to-test']
            &&
            body.repository.full_name in [
            'pingcap/tidb',
            'pingcap/tidb-dashboard',
            'pingcap/tidb-operator',
            'pingcap/tiflow',
            'tikv/client-go',
            'tikv/pd',
            'tikv/raft-engine',
            'tikv/tikv',
            ]
            &&
            body.pull_request.user.login in ['mittalrishabh', 'Tema', 'HaoW30']
  bindings:
    - ref: github-pr
  template:
    ref: ci-helper-for-pr
