apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: golang
      image: "ghcr.io/pingcap-qe/ci/jenkins:centos7-go1.21"
      command: [/tini, --, /bin/bash]
      tty: true
      resources:
        requests:
          memory: 24Gi
          cpu: 6000m
        limits:
          memory: 32Gi
          cpu: 8000m
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
