apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ee-cd
resources:
  - kaniko-build.yaml
  - ko-build-prow.yaml
  - pingcap-build-package-darwin.yaml
  - pingcap-build-package-linux.yaml
  - pingcap-release-ga.yaml
