import { parseArgs } from "jsr:@std/cli@1.0.17";
import { Octokit } from "https://esm.sh/@octokit/rest@21.1.1?dts";
import { RequestError } from "https://esm.sh/@octokit/request-error@6.1.8?dts";

const OWNERS_FILE_PATTERN = /(^|\/)(OWNERS|OWNERS_ALIASES)$/;
const BOT_EMAIL = "ti-community-prow-bot@tidb.io";
const BOT_NAME = "Ti Chi Robot";

interface CliArgs {
  owner: string;
  repository: string;
  source_branch: string;
  target_branch: string[];
  github_private_token: string;
}

type TreeItem = {
  path: string;
  mode?: "100644";
  type?: "blob";
  sha?: string | null;
};

function normalizeTargetBranches(targetBranches: string[]) {
  return [...new Set(targetBranches.filter(Boolean))];
}

function commitMessage(sourceBranch: string, targetBranch: string) {
  return `[SKIP CI] sync OWNERS from ${sourceBranch} to ${targetBranch}

skip-checks: true
Signed-off-by: ${BOT_NAME} <${BOT_EMAIL}>
`;
}

function pullRequestTitle(sourceBranch: string, targetBranch: string) {
  return `OWNERS: sync ${sourceBranch} to ${targetBranch}`;
}

function pullRequestBody(sourceBranch: string, targetBranch: string) {
  return `### What problem does this PR solve?

Sync \`OWNERS*\` files from \`${sourceBranch}\` to \`${targetBranch}\`.

### What changed and how does it work?

This PR was auto-generated by Prow and only updates \`OWNERS\` and \`OWNERS_ALIASES\` files.

/release-note-none
skip-issue-check
lgtm
approved
cherry-pick-approved
`;
}

async function getBranchCommitSha(
  octokit: Octokit,
  owner: string,
  repo: string,
  branch: string,
) {
  const { data } = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: `heads/${branch}`,
  });
  return data.object.sha;
}

async function getRecursiveOwnersTree(
  octokit: Octokit,
  owner: string,
  repo: string,
  branch: string,
) {
  const commitSha = await getBranchCommitSha(octokit, owner, repo, branch);
  const { data: commit } = await octokit.rest.git.getCommit({
    owner,
    repo,
    commit_sha: commitSha,
  });
  const { data: tree } = await octokit.rest.git.getTree({
    owner,
    repo,
    tree_sha: commit.tree.sha,
    recursive: "true",
  });

  const ownersFiles = new Map<string, string>();
  for (const item of tree.tree) {
    if (item.type !== "blob" || !item.path || !item.sha) {
      continue;
    }
    if (!OWNERS_FILE_PATTERN.test(item.path)) {
      continue;
    }
    ownersFiles.set(item.path, item.sha);
  }

  return { commitSha, ownersFiles };
}

async function readBlobText(
  octokit: Octokit,
  owner: string,
  repo: string,
  sha: string,
) {
  const { data } = await octokit.rest.git.getBlob({
    owner,
    repo,
    file_sha: sha,
  });
  return atob(data.content.replaceAll("\n", ""));
}

async function createBlob(
  octokit: Octokit,
  owner: string,
  repo: string,
  content: string,
) {
  const { data } = await octokit.rest.git.createBlob({
    owner,
    repo,
    content,
    encoding: "utf-8",
  });
  return data.sha;
}

function headBranchName(targetBranch: string) {
  return `bot/sync-owners-to-${targetBranch}`;
}

async function ensureHeadBranch(
  octokit: Octokit,
  owner: string,
  repo: string,
  headBranch: string,
  targetSha: string,
) {
  try {
    await octokit.rest.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${headBranch}`,
      sha: targetSha,
    });
    return;
  } catch (error) {
    if (!(error instanceof RequestError) || error.status !== 422) {
      throw error;
    }
  }

  await octokit.rest.git.updateRef({
    owner,
    repo,
    ref: `heads/${headBranch}`,
    sha: targetSha,
    force: true,
  });
}

async function syncOwnersForTarget(
  octokit: Octokit,
  owner: string,
  repo: string,
  sourceBranch: string,
  targetBranch: string,
) {
  const sourceState = await getRecursiveOwnersTree(
    octokit,
    owner,
    repo,
    sourceBranch,
  );
  const targetState = await getRecursiveOwnersTree(
    octokit,
    owner,
    repo,
    targetBranch,
  );

  const updates: TreeItem[] = [];

  for (const [path, sourceSha] of sourceState.ownersFiles.entries()) {
    const targetSha = targetState.ownersFiles.get(path);
    if (targetSha === sourceSha) {
      continue;
    }

    const content = await readBlobText(octokit, owner, repo, sourceSha);
    const blobSha = await createBlob(octokit, owner, repo, content);
    updates.push({
      path,
      mode: "100644",
      type: "blob",
      sha: blobSha,
    });
  }

  for (const path of targetState.ownersFiles.keys()) {
    if (sourceState.ownersFiles.has(path)) {
      continue;
    }
    updates.push({
      path,
      mode: "100644",
      type: "blob",
      sha: null,
    });
  }

  if (updates.length === 0) {
    return null;
  }

  const headBranch = headBranchName(targetBranch);
  await ensureHeadBranch(
    octokit,
    owner,
    repo,
    headBranch,
    targetState.commitSha,
  );

  const { data: headRef } = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: `heads/${headBranch}`,
  });
  const { data: headCommit } = await octokit.rest.git.getCommit({
    owner,
    repo,
    commit_sha: headRef.object.sha,
  });

  const { data: tree } = await octokit.rest.git.createTree({
    owner,
    repo,
    base_tree: headCommit.tree.sha,
    tree: updates,
  });

  const { data: commit } = await octokit.rest.git.createCommit({
    owner,
    repo,
    message: commitMessage(sourceBranch, targetBranch),
    tree: tree.sha,
    parents: [targetState.commitSha],
  });

  await octokit.rest.git.updateRef({
    owner,
    repo,
    ref: `heads/${headBranch}`,
    sha: commit.sha,
    force: true,
  });

  const { data: existingPulls } = await octokit.rest.pulls.list({
    owner,
    repo,
    state: "open",
    head: `${owner}:${headBranch}`,
    base: targetBranch,
  });

  if (existingPulls.length > 0) {
    return existingPulls[0].html_url;
  }

  const { data: pr } = await octokit.rest.pulls.create({
    owner,
    repo,
    title: pullRequestTitle(sourceBranch, targetBranch),
    body: pullRequestBody(sourceBranch, targetBranch),
    head: headBranch,
    base: targetBranch,
  });

  await octokit.rest.issues.addLabels({
    owner,
    repo,
    issue_number: pr.number,
    labels: [
      "skip-issue-check",
      "lgtm",
      "approved",
      "cherry-pick-approved",
    ],
  }).catch((error: RequestError) => {
    console.error(`failed to add labels for ${pr.html_url}`, error);
  });

  return pr.html_url;
}

async function main({
  owner,
  repository,
  source_branch,
  target_branch,
  github_private_token,
}: CliArgs) {
  const octokit = new Octokit({ auth: github_private_token });
  const targetBranches = normalizeTargetBranches(target_branch);

  for (const targetBranch of targetBranches) {
    const prUrl = await syncOwnersForTarget(
      octokit,
      owner,
      repository,
      source_branch,
      targetBranch,
    );
    if (prUrl) {
      console.info(prUrl);
    }
  }
}

const args = parseArgs<CliArgs>(Deno.args, {
  collect: ["target_branch"] as never[],
});

await main(args);
