import { parseArgs } from "jsr:@std/cli@1.0.17";
import { Octokit } from "https://esm.sh/@octokit/rest@21.1.1?dts";
import { RequestError } from "https://esm.sh/@octokit/request-error@6.1.8?dts";

const BOT_EMAIL = "ti-community-prow-bot@tidb.io";
const BOT_NAME = "Ti Chi Robot";

interface CliArgs {
  owner: string;
  repository: string;
  source_branch: string;
  target_branch: string[];
  github_private_token: string;
  notify_webhook_url?: string;
  dry_run?: boolean;
}

export function normalizeTargetBranches(targetBranches: string[]): string[] {
  return [...new Set(targetBranches.filter(Boolean))];
}

export function buildMergeCommitMessage(
  sourceBranch: string,
  targetBranch: string,
): string {
  return `Merge branch '${sourceBranch}' into ${targetBranch}

Auto-generated by Prow to keep '${targetBranch}' up to date with '${sourceBranch}'.

This is a regular merge commit: existing git tags (for example 'vX.Y.Z-fts')
and feature-specific commits on '${targetBranch}' are preserved. Tags are never
created, moved or deleted by this job.

Signed-off-by: ${BOT_NAME} <${BOT_EMAIL}>
`;
}

export function buildConflictPullRequestTitle(
  sourceBranch: string,
  targetBranch: string,
): string {
  return `sync ${sourceBranch} into ${targetBranch}`;
}

export function buildConflictPullRequestBody(
  sourceBranch: string,
  targetBranch: string,
): string {
  return `### What problem does this PR solve?

Keep \`${targetBranch}\` up to date with \`${sourceBranch}\`.

### What changed and how does it work?

The automated sync could not merge \`${sourceBranch}\` into \`${targetBranch}\`
because of merge conflicts. This pull request tracks the manual resolution.

Resolve the conflicts locally and push the merge commit to \`${targetBranch}\`:

\`\`\`bash
git fetch origin
git checkout ${targetBranch}
git merge origin/${sourceBranch}
# resolve the conflicts, then:
git push origin ${targetBranch}
\`\`\`

Once the merge commit is pushed, this pull request has nothing left to merge and
can be closed. The \`${targetBranch}\` specific git tags are not touched.
`;
}

async function branchExists(
  octokit: Octokit,
  owner: string,
  repo: string,
  branch: string,
): Promise<boolean> {
  try {
    await octokit.rest.git.getRef({
      owner,
      repo,
      ref: `heads/${branch}`,
    });
    return true;
  } catch (error) {
    if (error instanceof RequestError && error.status === 404) {
      return false;
    }
    throw error;
  }
}

type MergeResult = "merged" | "up-to-date" | "conflict" | "dry-run";

async function mergeSourceIntoTarget(
  octokit: Octokit,
  owner: string,
  repo: string,
  sourceBranch: string,
  targetBranch: string,
  dryRun: boolean,
): Promise<MergeResult> {
  if (dryRun) {
    console.info(
      `[dry-run] would merge '${sourceBranch}' into '${targetBranch}'.`,
    );
    return "dry-run";
  }

  try {
    const response = await octokit.rest.repos.merge({
      owner,
      repo,
      base: targetBranch,
      head: sourceBranch,
      commit_message: buildMergeCommitMessage(sourceBranch, targetBranch),
    });
    // 204 means the base branch already contains the head branch.
    return (response.status as number) === 204 ? "up-to-date" : "merged";
  } catch (error) {
    // 409 means the branches cannot be merged automatically.
    if (error instanceof RequestError && error.status === 409) {
      return "conflict";
    }
    throw error;
  }
}

async function ensureConflictPullRequest(
  octokit: Octokit,
  owner: string,
  repo: string,
  sourceBranch: string,
  targetBranch: string,
): Promise<string> {
  const { data: existingPulls } = await octokit.rest.pulls.list({
    owner,
    repo,
    state: "open",
    head: `${owner}:${sourceBranch}`,
    base: targetBranch,
  });
  if (existingPulls.length > 0) {
    return existingPulls[0].html_url;
  }

  const { data: pr } = await octokit.rest.pulls.create({
    owner,
    repo,
    title: buildConflictPullRequestTitle(sourceBranch, targetBranch),
    head: sourceBranch,
    base: targetBranch,
    body: buildConflictPullRequestBody(sourceBranch, targetBranch),
  });

  await octokit.rest.issues.addLabels({
    owner,
    repo,
    issue_number: pr.number,
    labels: ["skip-issue-check"],
  }).catch((error: RequestError) => {
    console.warn(
      `failed to add labels for ${pr.html_url}: ${error.message}`,
    );
  });

  return pr.html_url;
}

async function notifyByWebhook(
  webhookUrl: string | undefined,
  title: string,
  message: string,
) {
  if (!webhookUrl) {
    return;
  }

  const card = {
    config: { wide_screen_mode: true },
    header: {
      template: "orange",
      title: { content: title, tag: "plain_text" },
    },
    elements: [{ tag: "div", text: { content: message, tag: "lark_md" } }],
  };

  try {
    const response = await fetch(webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        msg_type: "interactive",
        card: JSON.stringify(card),
      }),
    });
    if (!response.ok) {
      console.warn(`failed to send notification: HTTP ${response.status}`);
    }
  } catch (error) {
    console.warn(`failed to send notification: ${error}`);
  }
}

async function syncTarget(
  octokit: Octokit,
  owner: string,
  repo: string,
  sourceBranch: string,
  targetBranch: string,
  notifyWebhookUrl: string | undefined,
  dryRun: boolean,
): Promise<boolean> {
  if (!await branchExists(octokit, owner, repo, targetBranch)) {
    console.warn(`target branch '${targetBranch}' does not exist, skipping.`);
    return false;
  }

  const result = await mergeSourceIntoTarget(
    octokit,
    owner,
    repo,
    sourceBranch,
    targetBranch,
    dryRun,
  );

  switch (result) {
    case "merged":
      console.info(`merged '${sourceBranch}' into '${targetBranch}'.`);
      return false;
    case "up-to-date":
      console.info(`'${targetBranch}' is already up to date.`);
      return false;
    case "dry-run":
      return false;
    case "conflict": {
      console.error(
        `cannot merge '${sourceBranch}' into '${targetBranch}' automatically: merge conflicts.`,
      );
      const prUrl = await ensureConflictPullRequest(
        octokit,
        owner,
        repo,
        sourceBranch,
        targetBranch,
      );
      console.error(`conflict resolution pull request: ${prUrl}`);
      await notifyByWebhook(
        notifyWebhookUrl,
        `Merge conflicts: ${sourceBranch} -> ${targetBranch}`,
        `The scheduled branch sync failed to merge **${sourceBranch}** into **${targetBranch}** because of merge conflicts.\n\n` +
          `Please resolve the conflicts and push the merge commit to **${targetBranch}**.\n\n` +
          `[Conflict resolution pull request](${prUrl})`,
      );
      return true;
    }
  }
}

async function main({
  owner,
  repository,
  source_branch,
  target_branch,
  github_private_token,
  notify_webhook_url,
  dry_run,
}: CliArgs) {
  const octokit = new Octokit({ auth: github_private_token });
  const targetBranches = normalizeTargetBranches(target_branch);

  if (targetBranches.length === 0) {
    console.error("no target branch specified.");
    Deno.exit(1);
  }

  if (!await branchExists(octokit, owner, repository, source_branch)) {
    console.error(`source branch '${source_branch}' does not exist.`);
    Deno.exit(1);
  }

  let hasConflict = false;
  for (const targetBranch of targetBranches) {
    const conflicted = await syncTarget(
      octokit,
      owner,
      repository,
      source_branch,
      targetBranch,
      notify_webhook_url,
      Boolean(dry_run),
    );
    hasConflict = hasConflict || conflicted;
  }

  if (hasConflict) {
    Deno.exit(1);
  }
}

if (import.meta.main) {
  const args = parseArgs<CliArgs>(Deno.args, {
    collect: ["target_branch"] as never[],
    boolean: ["dry_run"] as never[],
  });

  await main(args);
}
