apiVersion: "v1"
kind: "Pod"
spec:
  containers:
  - image: "hub.pingcap.net/jenkins/docker:20.10.24-dind"
    imagePullPolicy: "IfNotPresent"
    name: "dockerd"
    readinessProbe:
      exec:
        command: ["docker", "info"]
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 3
    env:
    - name: "DOCKER_TLS_CERTDIR"
      value: "/certs"
    resources:
      limits:
        memory: "32Gi"
        cpu: "16000m"
      requests:
        memory: "10Gi"
        cpu: "5000m"
    securityContext:
      privileged: true
    tty: false
    volumeMounts:
    - mountPath: "/home/jenkins"
      name: "volume-0"
      readOnly: false
    - mountPath: "/tmp"
      name: "volume-3"
      readOnly: false
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
    - mountPath: "/certs"
      name: "docker-certs"
      readOnly: false
  - command:
    - "cat"
    env:
    - name: "DOCKER_HOST"
      value: "tcp://localhost:2376"
    - name: "DOCKER_TLS_CERTDIR"
      value: "/certs"
    - name: "DOCKER_CERT_PATH"
      value: "/certs/client"
    - name: "DOCKER_TLS_VERIFY"
      value: "1"
    image: "hub.pingcap.net/jenkins/docker:20.10.24"
    imagePullPolicy: "Always"
    name: "docker"
    resources:
      requests:
        memory: "8Gi"
        cpu: "5000m"
    tty: true
    volumeMounts:
    - mountPath: "/home/jenkins"
      name: "volume-0"
      readOnly: false
    - mountPath: "/tmp"
      name: "volume-3"
      readOnly: false
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
    - mountPath: "/certs"
      name: "docker-certs"
      readOnly: false
  volumes:
  - emptyDir:
      medium: ""
    name: "volume-0"
  - emptyDir:
      medium: ""
    name: "workspace-volume"
  - emptyDir:
      medium: ""
    name: "volume-3"
  - name: "docker-certs"
    emptyDir:
      medium: ""
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
              - key: ci-nvme-high-performance
                operator: In
                values:
                  - "true"
