## You should run it firstly:
## kubectl port-forward -n ee-cd svc/el-public 8080

### pingcap/tidb-binlog push on master branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/release-8.0",
    "before": "00000000000000000000000000000000000000000",
    "after": "a7fae77dc59418da9d8971ffae3a7399e34e290f",
    "ref_type": "branch",
    "repository": {
        "name": "tidb-binlog",
        "clone_url": "https://github.com/pingcap/tidb-binlog",
        "owner": {
            "login": "pingcap"
        }
    }
}

### pingcap/tidb-binlog version tag created
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: create

{
  "ref": "v7.5.0",
  "ref_type": "tag",
  "repository": {
    "name": "tidb-binlog",
    "clone_url": "https://github.com/pingcap/tidb-binlog.git",
    "owner": {
      "login": "pingcap"
    }
  }
}
