apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: runner
      image: hub.pingcap.net/jenkins/rocky8_golang-1.25:latest
      tty: true
      env:
        - name: GOPATH
          value: /go
      resources:
        requests:
          memory: 8Gi
          cpu: "4"
        limits:
          memory: 8Gi
          cpu: "4"
    - name: net-tool
      image: hub.pingcap.net/jenkins/network-multitool
      tty: true
      resources:
        limits:
          memory: 128Mi
          cpu: 100m
    - name: utils
      image: ghcr.io/pingcap-qe/cd/utils/release:v2025.10.12-7-gfdd779c
      tty: true
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          cpu: "1"
          memory: 4Gi
    - name: mysql
      image: "hub.pingcap.net/jenkins/mysql:8.0.43"
      tty: true
      args:
        - "--server-id=1"
        - "--log-bin"
        - "--binlog-format=ROW"
        - "--default-authentication-plugin=mysql_native_password"
      env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "1"
      resources:
        limits:
          memory: 2Gi
          cpu: "1"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
