apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: golang
      image: "ghcr.io/pingcap-qe/ci/jenkins:v2026.1.18-8-gbb5ada9-go1.25"
      tty: true
      resources:
        requests:
          memory: 16Gi
          cpu: "6"
        limits:
          memory: 16Gi
          cpu: "6"
    - name: codecov
      image: python:3.11.10-bullseye
      tty: true
      resources:
        limits:
          memory: 4Gi
          cpu: 2000m
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
