apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: golang
      image: "hub.pingcap.net/jenkins/centos7_golang-1.20:latest"
      tty: true
      resources:
        requests:
          memory: 8Gi
          cpu: "4"
        limits:
          memory: 8Gi
          cpu: "4"
    - name: dockerd
      image: "docker:20.10.17-dind"
      tty: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        - name: DOCKER_REGISTRY_MIRROR
          value: https://registry-mirror.pingcap.net
      securityContext:
        privileged: true
      resources:
        requests:
          memory: 8Gi
          cpu: "4"
        limits:
          memory: 8Gi
          cpu: "4"
    - name: docker
      image: "hub.pingcap.net/jenkins/alpine-docker:tics-test"
      tty: true
      command:
        - "cat"
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      resources:
        requests:
          memory: 8Gi
          cpu: "4"
        limits:
          memory: 8Gi
          cpu: "4"
    - name: net-tool
      image: wbitt/network-multitool
      tty: true
      resources:
        limits:
          memory: 128Mi
          cpu: 100m
    - name: report
      image: hub.pingcap.net/jenkins/python3-requests:latest
      tty: true
      resources:
        limits:
          memory: 256Mi
          cpu: 100m
    - name: status-updater
      image: hub.pingcap.net/pingcap/github-status-updater:latest
      tty: true
      resources:
        limits:
          memory: 256Mi
          cpu: 100m
