apiVersion: v1
kind: Pod
spec:
  securityContext:
    runAsUser: 0
  containers:
    - name: golang
      image: "hub.pingcap.net/wangweizhen/tidb_image:go12320241009"
      securityContext:
        privileged: true
      tty: true
      resources:
        limits:
          memory: 32Gi
          cpu: "8"
      volumeMounts:
        - name: containerinfo
          mountPath: /etc/containerinfo
    - name: net-tool
      image: hub.pingcap.net/jenkins/network-multitool
      tty: true
      resources:
        limits:
          memory: 128Mi
          cpu: 100m
    - name: report
      image: hub.pingcap.net/jenkins/python3-requests:latest
      tty: true
      resources:
        limits:
          memory: 256Mi
          cpu: 100m
  volumes:
    - name: containerinfo
      downwardAPI:
        items:
          - path: cpu_limit
            resourceFieldRef:
              containerName: golang
              resource: limits.cpu
          - path: cpu_request
            resourceFieldRef:
              containerName: golang
              resource: requests.cpu
          - path: mem_limit
            resourceFieldRef:
              containerName: golang
              resource: limits.memory
          - path: mem_request
            resourceFieldRef:
              containerName: golang
              resource: requests.memory
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
              - key: ci-nvme-high-performance
                operator: In
                values:
                  - "true"
