apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: golang
      image: "us-docker.pkg.dev/pingcap-testing-account/internal/test/jenkins/rocky8_golang-1.23:latest"
      tty: true
      env:
        - name: GOPROXY
          value: "https://us-go.pkg.dev/pingcap-testing-account/go-proxy-remote|https://proxy.golang.org,direct"
      resources:
        requests:
          memory: 12Gi
          cpu: "4"
        limits:
          memory: 16Gi
          cpu: "6"
    - name: java
      image: "us-docker.pkg.dev/pingcap-testing-account/internal/test/jenkins/centos7_golang-1.13_java:cached"
      tty: true
      resources:
        requests:
          memory: 4Gi
          cpu: "2"
        limits:
          memory: 16Gi
          cpu: "4"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
