apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  initContainers:
    - name: init-mysql-config
      image: "us-docker.pkg.dev/pingcap-testing-account/ghcr-remote/pingcap-qe/ci/jenkins:v2026.3.29-14-g90ae7ef-go1.25"
      command:
        - sh
        - -c
        - |
          chmod 1777 /tmp/tidb
          echo "[client]" > /mysql-config/.my.cnf
          echo "ssl-mode=DISABLED" >> /mysql-config/.my.cnf
      volumeMounts:
        - mountPath: "/mysql-config"
          name: "mysql-config-volume"
        - mountPath: "/tmp/tidb"
          name: "tidb-temp-dir-volume"
  containers:
    - name: golang
      image: "us-docker.pkg.dev/pingcap-testing-account/ghcr-remote/pingcap-qe/ci/jenkins:v2026.3.29-14-g90ae7ef-go1.25"
      tty: true
      env:
        - name: GOPROXY
          value: "https://us-go.pkg.dev/pingcap-testing-account/go-proxy-remote|https://proxy.golang.org,direct"
      resources:
        requests:
          memory: 12Gi
          cpu: "2"
        limits:
          memory: 16Gi
          cpu: "4"
      volumeMounts:
        - mountPath: "/home/jenkins/.my.cnf"
          name: "mysql-config-volume"
          subPath: ".my.cnf"
        - mountPath: "/tmp/tidb"
          name: "tidb-temp-dir-volume"
    - name: utils
      image: us-docker.pkg.dev/pingcap-testing-account/ghcr-remote/pingcap-qe/cd/utils/release:v2025.10.12-7-gfdd779c
      tty: true
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          cpu: "1"
          memory: 4Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
              - key: ci-nvme-high-performance
                operator: In
                values:
                  - "true"
  volumes:
    - name: mysql-config-volume
      emptyDir: {}
    - name: tidb-temp-dir-volume
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 200Gi
            storageClassName: hyperdisk-rwo
