apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  initContainers:
    - name: download-sqllogic
      image: "ghcr.io/pingcap-qe/cd/utils/release:v2025.10.12-7-gfdd779c"
      command:
        - /bin/sh
        - -c
        - |
          cd /git && \
          oras pull hub-zot.pingcap.net/mirrors/hub/pingcap/case-data/sqllogic:v20241212 && \
          tar xzf sqllogictest_v20241212.tar.gz && \
          rm sqllogictest_v20241212.tar.gz
      volumeMounts:
        - name: test-data
          mountPath: /git
  containers:
    - name: golang
      image: "hub.pingcap.net/jenkins/rocky8_golang-1.23:latest"
      tty: true
      resources:
        requests:
          memory: 8Gi
          cpu: "4"
        limits:
          memory: 16Gi
          cpu: "6"
      volumeMounts:
        - name: test-data
          mountPath: /git
    - name: net-tool
      image: hub.pingcap.net/jenkins/network-multitool
      tty: true
      resources:
        limits:
          memory: 128Mi
          cpu: 100m
  volumes:
    - name: test-data
      emptyDir: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
              - key: ci-nvme-high-performance
                operator: In
                values:
                  - "true"
