apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: golang
      image: "hub.pingcap.net/jenkins/rocky8_golang-1.23:latest"
      tty: true
      resources:
        requests:
          memory: 16Gi
          cpu: "6"
        limits:
          memory: 16Gi
          cpu: "6"
    - name: utils
      image: ghcr.io/pingcap-qe/cd/utils/release:v2025.5.11-2-gfd3e259
      tty: true
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          cpu: "1"
          memory: 4Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
