apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: runner
      image: ghcr.io/pingcap-qe/ci/jenkins:v2026.3.15-1-g5625431-go1.25
      tty: true
      env:
        - name: GOPATH
          value: /go
      resources:
        requests:
          memory: 8Gi
          cpu: 2000m
        limits:
          memory: 8Gi
          cpu: 4000m
    - name: utils
      image: ghcr.io/pingcap-qe/cd/utils/release:v2025.10.12-7-gfdd779c
      tty: true
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          cpu: 1000m
          memory: 4Gi
    - name: mysql
      image: "us-docker.pkg.dev/pingcap-testing-account/dockerhub-remote/mysql:8.0.43"
      tty: true
      args:
        - "--server-id=1"
        - "--log-bin"
        - "--binlog-format=ROW"
        - "--default-authentication-plugin=mysql_native_password"
      env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "1"
      resources:
        requests:
          memory: 2Gi
          cpu: 500m
        limits:
          memory: 2Gi
          cpu: 1000m
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
