apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: git-push-pingcap-inc-tidb-linux
  labels:
    type: github-branch-push
    github-owner: pingcap-inc
    github-repo: tidb
spec:
  interceptors:
    - name: filter on repo owner and name and branches
      ref: { name: cel }
      params:
        - name: filter
          value: >-
            body.repository.full_name == 'pingcap-inc/tidb'
            &&
            body.ref.matches('^refs/heads/feature/release-8[.]5[.]5-active-active$')
  bindings:
    - ref: github-branch-push
    - ref: gcp-internal-build-params
    - { name: component, value: $(body.repository.name) }
    - { name: profile, value: release }
    - { name: timeout, value: 1h }
    - { name: source-ws-size, value: 50Gi }
    - { name: builder-resources-memory, value: 20Gi }
    - { name: builder-resources-cpu, value: "8" }
  template:
    ref: build-component-linux
