apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: golang
      image: "ghcr.io/pingcap-qe/ci/jenkins:v2024.10.8-119-g4e56df7-go1.21"
      tty: true
      resources:
        requests:
          memory: 12Gi
          cpu: 3000m
        limits:
          memory: 16Gi
          cpu: 6000m
    - name: utils
      image: ghcr.io/pingcap-qe/cd/utils/release:v2025.10.12-7-gfdd779c
      tty: true
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 4Gi
          cpu: 1000m
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
