apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: notified-successful-image-delivery-cloud-tidbx
  labels:
    type: github-issue-comment
spec:
  interceptors:
    - name: filter on github repo and comment content
      ref: { name: cel }
      params:
        - name: filter
          value: >-
            body.comment.body.matches('<!--\\s*META={.+?\\s*-->')
        - name: overlays
          value:
            - key: images
              expression: body.comment.body.split('<!--')[1].split('-->')[0].replace('META=', '').parseJSON().images.marshalJSON()
            - key: stage
              expression: body.comment.body.split('<!--')[1].split('-->')[0].replace('META=', '').parseJSON().stage
  bindings:
    - ref: github-issue-comment
    - { name: images, value: $(extensions.images) }
    - { name: stage, value: $(extensions.stage) }
  template:
    spec:
      params:
        - name: images
        - name: stage
      resourceTemplates:
        - apiVersion: tekton.dev/v1
          kind: TaskRun
          metadata:
            generateName: pingcap-notify-to-deliver-images-to-cloud-tidbx-
          spec:
            params:
              - name: images
                value: $(tt.params.images)
              - name: stage
                value: $(tt.params.stage)
            taskRef:
              name: pingcap-notify-to-update-ops-tidbx
            workspaces:
              - name: notify-config
                secret:
                  secretName: image-delivery-notify-config-tidbx
              - name: ops-config
                secret:
                  secretName: image-delivery-ops-config-tidbx
