apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: runner
      image: ghcr.io/pingcap-qe/cd/builders/tiflash:v2025.4.15-rocky8-llvm-17.0.6-v2
      command:
        - "/bin/bash"
        - "-c"
        - "cat"
      tty: true
      resources:
        requests:
          memory: 24Gi
          cpu: "6"
          ephemeral-storage: 20Gi
        limits:
          memory: 32Gi
          cpu: "8"
          ephemeral-storage: 150Gi
      volumeMounts:
        - mountPath: "/tmp"
          name: "tmp"
          readOnly: false
    - name: utils
      image: ghcr.io/pingcap-qe/cd/utils/release:v2025.10.12-7-gfdd779c
      args: ["sleep", "infinity"]
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "4Gi"
  volumes:
    - name: "tmp"
      emptyDir: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
