apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: runner
      image: ghcr.io/pingcap-qe/cd/builders/tiflash:v2025.4.15-rocky8-llvm-17.0.6-v2
      imagePullPolicy: Always
      command:
        - "cat"
      tty: true
      resources:
        requests:
          memory: "32Gi"
          cpu: "12"
          ephemeral-storage: 20Gi
      volumeMounts:
        - mountPath: "/home/jenkins/agent/rust"
          name: "volume-0"
          readOnly: false
        - mountPath: "/tmp"
          name: "volume-6"
          readOnly: false
        - mountPath: "/tmp-memfs"
          name: "volume-7"
          readOnly: false
  volumes:
    - name: "volume-0"
      emptyDir: {}
    - name: "volume-6"
      emptyDir: {}
    - name: "volume-7"
      emptyDir:
        medium: Memory
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
