apiVersion: "v1"
kind: "Pod"
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - image: "docker:24.0.9-dind"
      imagePullPolicy: "IfNotPresent"
      name: "dockerd"
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        - name: DOCKER_DRIVER
          value: overlay2
      resources:
        limits:
          memory: "32Gi"
          cpu: "8"
          ephemeral-storage: 150Gi
        requests:
          memory: "16Gi"
          cpu: "4"
          ephemeral-storage: 20Gi
      securityContext:
        privileged: true
      tty: false
      volumeMounts:
        - mountPath: "/tmp"
          name: "tmp"
          readOnly: false
        - mountPath: "/var/lib/docker"
          name: "docker-graph"
    - command:
        - "cat"
      env:
        - name: "DOCKER_HOST"
          value: "tcp://localhost:2375"
        - name: DOCKER_TLS_CERTDIR
          value: ""
      image: ghcr.io/pingcap-qe/ci/base:v2026.4.12-11-g402978f-go1.25
      imagePullPolicy: "Always"
      name: "docker"
      resources:
        requests:
          memory: "16Gi"
          cpu: "4"
          ephemeral-storage: 10Gi
        limits:
          memory: "32Gi"
          cpu: "8"
          ephemeral-storage: 50Gi
      tty: true
      volumeMounts:
        - mountPath: "/tmp"
          name: "tmp"
          readOnly: false
  volumes:
    - emptyDir:
        medium: ""
      name: "tmp"
    - name: "docker-graph"
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 200Gi
            storageClassName: hyperdisk-rwo
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
