apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: tag-create-tikv-tikv
  labels:
    type: github-tag-create
    github-owner: tikv
    github-repo: tikv
spec:
  interceptors:
    - name: filter on repo owner and name and branches
      ref: { name: cel }
      params:
        - name: filter
          value: >-
            body.repository.owner.login == 'tikv'
            &&
            body.repository.name == 'tikv'
            &&
            body.ref.matches('^v[0-9]+[.][0-9]+[.][0-9]+(-(alpha|beta|rc)([.][0-9]+)?([.]pre)?)?$')

  bindings:
    - ref: github-tag-create
  template:
    ref: bump-tikv-cargo-pkg-version
