apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: github-push-tidb-build-next-gen
  labels:
    type: github-branch-push
    github-owner: pingcap
    profile: next-gen
spec:
  interceptors:
    - name: filter on repo
      ref: { name: cel }
      params:
        - name: filter
          value: >-
            body.repository.full_name == 'pingcap/tidb'
            &&
            body.ref.matches('^refs/heads/(master|release-nextgen-[0-9]+|feature/next-gen.*)$')

  bindings:
    - ref: github-branch-push
    - { name: component, value: $(body.repository.name) }
    - { name: os, value: linux }
    - { name: profile, value: next-gen }
    - { name: timeout, value: 45m }
    - { name: source-ws-size, value: 50Gi }
    - { name: builder-resources-memory, value: 32Gi }
    - { name: builder-resources-cpu, value: "8" }
  template:
    ref: build-component

---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: git-push-pingcap-tidb-build-enterprise-without-plugins
  labels:
    type: github-branch-push
    github-owner: pingcap
    github-repo: tidb
    profile: enterprise-without-plugins
spec:
  interceptors:
    - name: filter on repo owner and name and branches
      ref:
        name: cel
      params:
        - name: filter
          # support branches:
          # - feature/release-X.Y-*
          value: >-
            body.repository.full_name == 'pingcap/tidb'
            &&
            body.ref.matches('^refs/heads/(feature/release-[7-9]+[.][0-9]+-.*)$')

  bindings:
    - ref: github-branch-push
    - { name: component, value: $(body.repository.name) }
    - { name: os, value: linux }
    - { name: profile, value: enterprise-without-plugins }
    - { name: timeout, value: 45m }
    - { name: source-ws-size, value: 50Gi }
    - { name: builder-resources-memory, value: 32Gi }
    - { name: builder-resources-cpu, value: "8" }
  template:
    ref: build-component
