## You should run it firstly:
## kubectl port-forward -n ee-cd svc/el-public 8080

### pingcap/tidb: push on master branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/master",
    "before": "00000000000000000000000000000000000000000",
    "after": "c52655cd198b11cd0fae18d6d7b9305ad74783ee",
    "ref_type": "branch",
    "repository": {
        "name": "tidb",
        "clone_url": "https://github.com/pingcap/tidb.git",
        "owner": {
            "login": "pingcap"
        }
    }
}

### pingcap/tidb version tag created
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: create

{
  "ref": "v7.5.0",
  "ref_type": "tag",
  "repository": {
    "name": "tidb",
    "clone_url": "https://github.com/pingcap/tidb.git",
    "owner": {
      "login": "pingcap"
    }
  }
}

### pingcap/tidb hotfix branch created
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: create

{
  "ref": "release-7.5-20240125-v7.5.0",
  "ref_type": "branch",
  "repository": {
    "name": "tidb",
    "clone_url": "https://github.com/pingcap/tidb.git",
    "owner": {
      "login": "pingcap"
    }
  }
}
