apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: runner
      image: "hub.pingcap.net/jenkins/tikv-cached-master:latest"
      tty: true
      resources:
        requests:
          memory: 32Gi
          cpu: "16"
        limits:
          memory: 40Gi
          cpu: "16"
      volumeMounts:
      - mountPath: "/home/jenkins/agent/memvolume"
        name: "volume-memory"
        readOnly: false
      - mountPath: "/tmp"
        name: "volume-tmp"
        readOnly: false
    - name: net-tool
      image: hub.pingcap.net/jenkins/network-multitool
      tty: true
      resources:
        limits:
          memory: 128Mi
          cpu: 100m
  volumes:
  - emptyDir:
      medium: ""
    name: "volume-tmp"
  - emptyDir:
      medium: ""
    name: "volume-home"
  - emptyDir:
      medium: Memory
    name: "volume-memory"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
              - key: ci-nvme-high-performance
                operator: In
                values:
                  - "true"
