# yaml-language-server: $schema=https://github.com/redhat-developer/vscode-tekton/raw/refs/heads/main/scheme/tekton.dev/v1_Task.json
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: pingcap-notify-to-deliver-images-to-cloud-tidbx
  labels:
    app.kubernetes.io/version: "0.2.0"
  annotations:
    tekton.dev/pipelines.minVersion: "1.0.0"
    tekton.dev/categories: delivery
    tekton.dev/tags: images,delivery,cloud,tidbx
    tekton.dev/displayName: "Notify to deliver images to cloud regions"
    tekton.dev/platforms: "linux/amd64,linux/arm64"
spec:
  params:
    - name: src
      description: images list
    - name: publisher-url
      type: string
      description: publisher url
      default: "http://publisher.publisher.svc"
  stepTemplate:
    image: ghcr.io/pingcap-qe/cd/utils/release:v2025.10.26-5-ge8130cb
  steps:
    - name: request-kernel-image-sync
      ref:
        name: request-kernel-image-sync
      params:
        - name: src
          value: $(params.src)
        - name: publisher-url
          value: $(params.publisher-url)
        - name: stages
          value: "dev prod"
