apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: rust
      image: "hub.pingcap.net/tiflash/tiflash-llvm-base:amd64"
      tty: true
      resources:
        requests:
          memory: 8Gi
          cpu: "2"
        limits:
          memory: 16Gi
          cpu: "6"
      command: [/bin/sh, -c]
      args: [cat]
    - name: net-tool
      image: wbitt/network-multitool
      tty: true
      resources:
        limits:
          memory: 128Mi
          cpu: 200m
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
