apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: golang
      image: "us-docker.pkg.dev/pingcap-testing-account/internal/test/wangweizhen/tidb_image:go12320241009"
      securityContext:
        privileged: true
      tty: true
      env:
        - name: GOPROXY
          value: "https://us-go.pkg.dev/pingcap-testing-account/go-proxy-remote|https://proxy.golang.org,direct"
      resources:
        requests:
          cpu: "8"
          memory: 32Gi
          ephemeral-storage: 20Gi
        limits:
          memory: 64Gi
          cpu: "16"
          ephemeral-storage: 150Gi
      volumeMounts:
        - mountPath: /home/jenkins/.tidb
          name: bazel-out-merged
        - name: bazel-rc # migration: keep
          mountPath: /data/
          readOnly: true
        - name: containerinfo # migration: keep
          mountPath: /etc/containerinfo
      lifecycle:
        postStart:
          exec:
            command:
              - /bin/sh
              - /data/bazel-prepare-in-container.sh
  volumes:
    - name: bazel-out-merged
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 150Gi
            storageClassName: hyperdisk-rwo
    - name: bazel-rc
      configMap:
        name: bazel
    - name: containerinfo
      downwardAPI:
        items:
          - path: cpu_limit
            resourceFieldRef:
              containerName: golang
              resource: limits.cpu
          - path: cpu_request
            resourceFieldRef:
              containerName: golang
              resource: requests.cpu
          - path: mem_limit
            resourceFieldRef:
              containerName: golang
              resource: limits.memory
          - path: mem_request
            resourceFieldRef:
              containerName: golang
              resource: requests.memory
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
