apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  initContainers:
    - name: download-sqllogic
      image: "us-docker.pkg.dev/pingcap-testing-account/ghcr-remote/pingcap-qe/cd/utils/release:v2025.10.12-7-gfdd779c"
      command:
        - /bin/sh
        - -c
        - |
          cd /git && \
          oras pull us-docker.pkg.dev/pingcap-testing-account/hub/pingcap/case-data/sqllogic:v20241212 && \
          tar xzf sqllogictest_v20241212.tar.gz && \
          rm sqllogictest_v20241212.tar.gz
      volumeMounts:
        - name: test-data
          mountPath: /git
  containers:
    - name: golang
      image: "us-docker.pkg.dev/pingcap-testing-account/ghcr-remote/pingcap-qe/ci/jenkins:v2026.3.29-14-g90ae7ef-go1.25"
      tty: true
      env:
        - name: GOPROXY
          value: "https://us-go.pkg.dev/pingcap-testing-account/go-proxy-remote|https://proxy.golang.org,direct"
      resources:
        requests:
          memory: 8Gi
          cpu: "4"
        limits:
          memory: 16Gi
          cpu: "6"
      volumeMounts:
        - name: test-data
          mountPath: /git
  volumes:
    - name: workspace-volume
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 150Gi
            storageClassName: hyperdisk-rwo
    - name: test-data
      emptyDir: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
