apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: github-push-tiflash-build-next-gen
  labels:
    type: github-branch-push
    github-owner: pingcap
    profile: next-gen
spec:
  interceptors:
    - name: filter on repo
      ref: { name: cel }
      params:
        - name: filter
          value: >-
            body.repository.full_name == 'pingcap/tiflash'
            &&
            body.ref.matches('^refs/heads/(master|release-nextgen-[0-9]+|feature/next-gen.*)$')

  bindings:
    - ref: github-branch-push
    - { name: component, value: $(body.repository.name) }
    - { name: profile, value: next-gen }
    - { name: timeout, value: 2h }
    - { name: source-ws-size, value: 100Gi }
    - { name: builder-resources-cpu, value: "16" }
    - { name: builder-resources-memory, value: "64Gi" }

  template:
    ref: build-component
