apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  initContainers:
    - name: init-mysql-config
      image: "hub.pingcap.net/jenkins/rocky8_golang-1.23:latest"
      command:
        - sh
        - -c
        - |
          echo "[client]" > /mysql-config/.my.cnf
          echo "ssl-mode=DISABLED" >> /mysql-config/.my.cnf
      volumeMounts:
        - mountPath: "/mysql-config"
          name: "mysql-config-volume"
  containers:
    - name: golang
      image: "hub.pingcap.net/jenkins/rocky8_golang-1.23:latest"
      tty: true
      resources:
        requests:
          memory: 12Gi
          cpu: "4"
        limits:
          memory: 16Gi
          cpu: "6"
      volumeMounts:
        - mountPath: "/home/jenkins/.my.cnf"
          name: "mysql-config-volume"
          subPath: ".my.cnf"
    - name: mysql1
      image: 'hub.pingcap.net/jenkins/mysql:5.7'
      tty: true
      resources:
        limits:
          memory: 4Gi
          cpu: "2"
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: '123456'
      args:
        - "--ssl=ON"
        - "--log-bin"
        - "--binlog-format=ROW"
        - "--enforce-gtid-consistency=ON"
        - "--gtid-mode=ON"
        - "--server-id=1"
        - "--default-authentication-plugin=mysql_native_password"
    - name: mysql2
      image: 'hub.pingcap.net/jenkins/mysql:5.7'
      tty: true
      resources:
        limits:
          memory: 4Gi
          cpu: "2"
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: '123456'
        - name: MYSQL_TCP_PORT
          value: '3307'
      args:
        - "--ssl=ON"
        - "--log-bin"
        - "--binlog-format=ROW"
        - "--enforce-gtid-consistency=ON"
        - "--gtid-mode=ON"
        - "--server-id=1"
        - "--default-authentication-plugin=mysql_native_password"
    - name: net-tool
      image: hub.pingcap.net/jenkins/network-multitool
      tty: true
      resources:
        limits:
          memory: 128Mi
          cpu: 100m
  volumes:
    - name: mysql-config-volume
      emptyDir: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64

