apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: golang
      image: "hub.pingcap.net/jenkins/rocky8_golang-1.23:latest"
      tty: true
      resources:
        limits:
          memory: 8Gi
          cpu: "4"
      volumeMounts:
        - name: volume-tmp
          mountPath: /tmp
        - name: volume-docker
          mountPath: /var/lib/docker
    - name: dockerd
      image: "docker:20.10.17-dind"
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        - name: DOCKER_REGISTRY_MIRROR
          value: "https://registry-mirror.pingcap.net/"
      resources:
        limits:
          memory: 16Gi
          cpu: "6"
      volumeMounts:
        - name: volume-docker
          mountPath: /var/lib/docker
        - name: volume-tmp
          mountPath: /tmp
    - name: docker
      image: 'hub.pingcap.net/tiflow/dind:alpine-docker-go1.23'
      imagePullPolicy: Always
      tty: true
      env:
        - name: DOCKER_HOST
          value: 'tcp://localhost:2375'
      command:
        - "cat"
      resources:
        limits:
          memory: 16Gi
          cpu: "6"
      volumeMounts:
        - name: volume-docker
          mountPath: /var/lib/docker
        - name: volume-tmp
          mountPath: /tmp
    - name: net-tool
      image: hub.pingcap.net/jenkins/network-multitool
      tty: true
      resources:
        limits:
          memory: 128Mi
          cpu: 100m
  volumes:
    - name: "volume-docker"
      emptyDir: {}
    - name: "volume-tmp"
      emptyDir: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
