node('build_go1130') {
    stage('Checkout') {
        checkout scm
    }
    dir('./sync_ci'){
        stage('Build') {
            echo 'Building....'
            sh 'make'
        }
        stage('Test') {
            echo 'Testing....'
            sh 'GO111MODULE=on go test -c ./pkg/parser && ./parser.test'
        }
    }
}
node('SOME_DEPLOY_SERVER') {
    dir('./sync_ci'){
        stage('Deploy') {
            echo 'Deploying....'
            checkout scm
            if (currentBuild.result == null || currentBuild.result == 'SUCCESS') { 
                withCredentials([string(credentialsId: 'sync_ci_dsn', variable: 'dsn'), string(credentialsId: 'sync_ci_gh', variable: 'gh'), string(credentialsId: 'sync_ci_tk', variable: 'tk'), string(credentialsId: 'sync_ci_ui', variable: 'ui'), string(credentialsId: 'sync_ci_wc', variable: 'wc')]) {
                    sh 'sudo make install dsn="${dsn}" gh="${gh}" ui=${ui} tk="${tk}" wc="${wc}"'
                }
                sh 'sudo systemctl restart sync-ci.service'
                        //sh 'curl 127.0.0.1:36000/ping'
            }
        }
    }
}