node {
    def root = tool type: 'go', name: 'Go 1.15'
    stage('Checkout') {
        checkout scm
    }
    dir('./sync_ci'){
        withEnv(["GOROOT=${root}", "PATH+GO=${root}/bin"]) {
            stage('Build') {
                echo 'Building....'
                sh 'make'
            }
            stage('Test') {
                echo 'Testing....'
                sh 'GO111MODULE=on go test -c ./pkg/parser && ./parser.test'
            }
            stage('Deploy') {
                echo 'Deploying....'
                if (currentBuild.result == null || currentBuild.result == 'SUCCESS') { 
                    withCredentials([string(credentialsId: 'sync_ci_dsn', variable: 'dsn'), string(credentialsId: 'sync_ci_gh', variable: 'gh'), string(credentialsId: 'sync_ci_tk', variable: 'tk'), string(credentialsId: 'sync_ci_ui', variable: 'ui'), string(credentialsId: 'sync_ci_wc', variable: 'wc')]) {
                        sh 'echo $dsn'
                        sh 'sudo make install dsn="${dsn}" gh="${gh}" ui=${ui} tk="${tk}"  wc="${wc}" GOROOT=${GOROOT} PATH=${GOROOT}/bin:$PATH'
                    }
                    sh 'sudo systemctl restart sync-ci.service'
                    //sh 'curl 127.0.0.1:36000/ping'
                }
            }
        }
    }
}
