apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: zookeeper
      image: wurstmeister/zookeeper
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 200m
          memory: 4Gi
        limits:
          cpu: 2000m
          memory: 4Gi
      tty: true
      volumeMounts:
        - mountPath: /tmp
          name: volume-0
    - name: kafka
      image: wurstmeister/kafka:2.12-2.4.1
      imagePullPolicy: IfNotPresent
      env:
        - name: KAFKA_CREATE_TOPICS
          value: big-message-test:1:1
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: localhost:2181
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "11534336"
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "11534336"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://127.0.0.1:9092
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://127.0.0.1:9092
        - name: ZK
          value: zk
      resources:
        requests:
          cpu: 200m
          memory: 4Gi
        limits:
          cpu: 2000m
          memory: 4Gi
      tty: true
      volumeMounts:
        - mountPath: /tmp
          name: volume-0
    - args:
        - cat
      image: hub.pingcap.net/jenkins/golang-tini:1.21
      imagePullPolicy: Always
      name: golang
      resources:
        requests:
          cpu: "2"
          memory: 12Gi
        limits:
          cpu: "4"
          memory: 16Gi
      tty: true
      volumeMounts:
        - mountPath: /tmp
          name: volume-0
    - name: net-tool
      image: hub.pingcap.net/jenkins/network-multitool
      tty: true
      resources:
        limits:
          memory: 128Mi
          cpu: 100m
  volumes:
    - emptyDir: {}
      name: volume-0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
