apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: runner
      image: ghcr.io/pingcap-qe/cd/builders/tiflash:v2025.4.15-rocky8-llvm-17.0.6-v2
      imagePullPolicy: Always
      command:
        - "/bin/bash"
        - "-c"
        - "cat"
      tty: true
      resources:
        requests:
          memory: 32Gi
          cpu: "12"
          ephemeral-storage: 20Gi
        limits:
          memory: 64Gi
          cpu: "12"
          ephemeral-storage: 150Gi
      volumeMounts:
        - mountPath: "/tmp"
          name: "tmp"
  volumes:
    - name: "tmp"
      emptyDir: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
