apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: golang
      image: "hub.pingcap.net/wangweizhen/tidb_image:go11920220922"
      securityContext:
        privileged: true
      tty: true
      resources:
        requests:
          memory: 8Gi
          cpu: "6"
        limits:
          memory: 12Gi
          cpu: "8"
      # env:
      #   - name: GOPATH
      #     value: /share/.go
      #   - name: GOCACHE
      #     value: /share/.cache/go-build
      volumeMounts:
        - mountPath: /home/jenkins/.tidb/tmp
          name: bazel-out-merged
        - name: bazel-out-lower
          subPath: tidb/go1.19
          mountPath: /bazel-out-lower
        - name: bazel-out-overlay
          mountPath: /bazel-out-overlay
        - name: gocache
          mountPath: /share/.cache/go-build
        - name: gopathcache
          mountPath: /share/.go
        - name: bazel-rc
          mountPath: /data/
          readOnly: true
        - name: containerinfo
          mountPath: /etc/containerinfo
      lifecycle:
        postStart:
          exec:
            command:
              - /bin/sh
              - /data/bazel-prepare-in-container.sh
    - name: net-tool
      image: hub.pingcap.net/jenkins/network-multitool
      tty: true
      resources:
        limits:
          memory: 128Mi
          cpu: 100m
    - name: report
      image: hub.pingcap.net/jenkins/python3-requests:latest
      tty: true
      resources:
        limits:
          memory: 256Mi
          cpu: 100m
  volumes:
    - name: gopathcache
      persistentVolumeClaim:
        claimName: gopathcache
    - name: gocache
      persistentVolumeClaim:
        claimName: gocache
    - name: bazel-out-lower
      persistentVolumeClaim:
        claimName: bazel-out-data
    - name: bazel-out-overlay
      emptyDir: {}
    - name: bazel-out-merged
      emptyDir: {}
    - name: bazel-rc
      secret:
        secretName: bazel
    - name: containerinfo
      downwardAPI:
        items:
          - path: cpu_limit
            resourceFieldRef:
              containerName: golang
              resource: limits.cpu
          - path: cpu_request
            resourceFieldRef:
              containerName: golang
              resource: requests.cpu
          - path: mem_limit
            resourceFieldRef:
              containerName: golang
              resource: limits.memory
          - path: mem_request
            resourceFieldRef:
              containerName: golang
              resource: requests.memory
    - name: utils
      image: ghcr.io/pingcap-qe/cd/utils/release:v2025.10.12-7-gfdd779c
      tty: true
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          cpu: "1"
          memory: 4Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
