apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: tag-create-pingcap-tidb-operator
  labels:
    type: github-tag-create
    github-owner: pingcap
    github-repo: tidb-operator
spec:
  interceptors:
    - name: filter on repo owner and name and tags
      ref: { name: cel }
      params:
        - name: filter
          value: >-
            body.repository.full_name == 'pingcap/tidb-operator'
            &&
            body.ref.matches('^v[0-9]+[.][0-9]+[.][0-9]+(-.+)?$')

  bindings:
    - ref: github-tag-create
    - ref: ksy-classic-build-params
    - { name: builder-resources-memory, value: 8Gi }
    - { name: builder-resources-cpu, value: "2" }
    - { name: component, value: $(body.repository.name) }
    - { name: os, value: linux }
    - { name: profile, value: release }
    - { name: source-ws-size, value: 10Gi }
    - { name: timeout, value: 30m }

  template:
    ref: build-component-linux
