apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: branch-create-product-components-hotfix
  labels:
    type: github-branch-create
spec:
  interceptors:
    - name: filter on repo and branches
      ref:
        name: cel
      params:
        - name: filter
          value: >-
            body.repository.full_name in [
            'pingcap/tidb',
            'pingcap/tiflash',
            'pingcap/tiflow',
            'pingcap/ticdc',
            'pingcap/tidb-binlog',
            'pingcap/tidb-dashboard',
            'pingcap/tidb-tools',
            'tikv/tikv',
            'tikv/pd',
            ]
            &&
            body.ref.matches('^release-[0-9]+[.][0-9]+-[0-9]+-v[0-9]+[.][0-9]+[.][0-9]+(-.+)?$')

  bindings:
    - ref: github-branch-create
  template:
    ref: sync-owners-for-hotfix-branch
---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: branch-create-pingcap-org-bump-placeholder
  labels:
    type: github-branch-create
    github-owner: pingcap
spec:
  interceptors:
    - name: filter on repo owner and name and branches
      ref: { name: cel }
      params:
        - name: filter
          value: >-
            body.repository.full_name in [
            'pingcap/monitoring',
            'pingcap/ng-monitoring',
            'pingcap/tidb-binlog',
            'pingcap/tidb-dashboard',
            ]
            &&
            body.ref.matches('^release-[0-9]+[.][0-9]+(-beta[.][0-9]+)?$')
  bindings:
    - ref: github-branch-create
  template:
    ref: bump-placeholder-version-in-readme
