apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: tag-create-pingcap-org-bump-placeholder
  labels:
    type: github-tag-create
    github-owner: pingcap
spec:
  interceptors:
    - name: filter on repo owner and name and tags
      ref: { name: cel }
      params:
        - name: filter
          value: >-
            body.repository.full_name in [
            'pingcap/monitoring',
            'pingcap/ng-monitoring',
            'pingcap/tidb-binlog',
            'pingcap/tidb-dashboard',
            'pingcap/tiflow',
            ]
            &&
            body.ref.matches('^v[0-9]+[.][0-9]+[.][0-9]+(-(alpha|beta)([.][0-9]+.*)?)?$')
  bindings:
    - ref: github-tag-create
  template:
    ref: bump-placeholder-version-in-readme
