apiVersion: batch/v1
kind: CronJob
metadata:
  name: shrink-ci-pipeline-cache
  namespace: jenkins-tidb
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          nodeSelector:
            resourcepool: ksyun-ci  
          containers:
            - name: deno
              image: "denoland/deno:1.25.1"
              tty: true
              args:
                - run 
                - --allow-all 
                - https://github.com/PingCAP-QE/ci/raw/main/scripts/plugins/s3-cache.ts
                - --op=shrink
                - --keep-size-g=200
              env:
                - name: DENO_DIR
                  value: /share/.deno
              envFrom:
                - secretRef:
                    name: ci-pipeline-cache
                - configMapRef:
                    name: ci-pipeline-cache
              volumeMounts:
                - name: deno-dir
                  mountPath: /share/.deno
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "100m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"
          volumes:
            - name: deno-dir
              persistentVolumeClaim:
                claimName: deno-dir
