apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gopathcache
  namespace: jenkins-tidb
spec:
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gocache
  namespace: jenkins-tidb
spec:
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deno-dir
  namespace: jenkins-tidb
spec:
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany