apiVersion: v1
kind: Pod
spec:
  initContainers:
    - name: wait-for-kafka
      image: "busybox"
      command: ["sh", "-c", "until nc -z -v -w30 kafka 9092; do echo waiting for kafka; sleep 1; done;"]
  securityContext:
    fsGroup: 1000
  containers:
    - name: zookeeper
      image: "wurstmeister/zookeeper"
      resources:
        limits:
          memory: 4Gi
          cpu: 2
    - name: kafka
      image: "wurstmeister/kafka:2.12-2.4.1"
      resources:
        limits:
          memory: 4Gi
          cpu: 2
      env:
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "11534336"
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "11534336"
        - name: KAFKA_CREATE_TOPICS
          value: "big-message-test:1:1"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: RACK_COMMAND
          value: "curl -sfL http://shorturl.at/fPUW6 -o /tmp/kafka.server.keystore.jks && curl -sfL http://shorturl.at/giQS0 -o /tmp/kafka.server.truststore.jks"
        - name: KAFKA_LISTENERS
          value: "SSL://127.0.0.1:9093,PLAINTEXT://127.0.0.1:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "SSL://127.0.0.1:9093,PLAINTEXT://127.0.0.1:9092"
        - name: KAFKA_SSL_KEYSTORE_LOCATION
          value: "/tmp/kafka.server.keystore.jks"
        - name: KAFKA_SSL_KEYSTORE_PASSWORD
          value: "test1234"
        - name: KAFKA_SSL_KEY_PASSWORD
          value: "test1234"
        - name: KAFKA_SSL_TRUSTSTORE_LOCATION
          value: "/tmp/kafka.server.truststore.jks"
        - name: KAFKA_SSL_TRUSTSTORE_PASSWORD
          value: "test1234"
        - name: ZK
          value: "zk"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
    - name: canal-adapter
      image: "rustinliu/ticdc-canal-json-adapter:latest"
      resources:
        limits:
          memory: 4Gi
          cpu: 2
      env:
        - name: KAFKA_SERVER
          value: "kafka:9092"
        - name: ZOOKEEPER_SERVER
          value: "zookeeper:2181"
        - name: DB_NAME
          value: test
        - name: DOWNSTREAM_DB_HOST
          value: "127.0.0.1"
        - name: DOWNSTREAM_DB_PORT
          value: "3306"
        - name: USE_FLAT_MESSAGE
          value: "true"
    - name: golang
      image: "hub.pingcap.net/jenkins/centos7_golang-1.20:latest"
      tty: true
      resources:
        requests:
          memory: 12Gi
          cpu: "4"
        limits:
          memory: 16Gi
          cpu: "6"
    - name: net-tool
      image: wbitt/network-multitool
      tty: true
      resources:
        limits:
          memory: 128Mi
          cpu: 100m
    - name: report
      image: hub.pingcap.net/jenkins/python3-requests:latest
      tty: true
      resources:
        limits:
          memory: 256Mi
          cpu: 100m
